const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], L=[.299,.587,.114];
const luminance=v=>v?L.reduce((s,w,i)=>s+w*v[i],0):0, fmt=(v,n=4)=>Number.isFinite(v)?Number(v).toPrecision(n):'—';
const rgb=v=>v?`(${v.map(x=>fmt(x)).join(', ')})`:'—', clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
let trace=null, selected=null, filtered=[], selectedComponent=null, intervention=null, volumeIndex=0, samplerData=null, meshEdges=[], baseDefault='';
const state={tab:'why',mode:'exact',presentation:false,isolated:false,yaw:-.65,pitch:.3,zoom:1.25,panX:0,panY:0};

const img=new Image(); img.src='/results/d1_official_demo/ours_final.png'; img.onload=()=>$('#image').getContext('2d').drawImage(img,0,0,256,256);
function kv(label,value){return `<div class="kv"><b>${label}</b><strong>${value??'—'}</strong></div>`}
function metric(label,value){return `<div class="metric"><span>${label}</span><code>${value??'—'}</code></div>`}
function swatch(label,v){const c=v.map(x=>Math.round(255*clamp(x)));return `<div class="swatch" style="background:rgb(${c})">${label}</div>`}
function updateURL(){if(!trace)return;const q=new URLSearchParams({pixel:trace.pixel.join(','),mode:state.mode,tab:state.tab});if(selected)q.set('path',selected.id);history.replaceState(null,'','?'+q)}
function setTab(id){state.tab=id;$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));updateURL();if(id==='where')draw3D();if(id==='nerf')drawVolume()}
$$('#tabs button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
$('#presentation').onclick=()=>{state.presentation=!state.presentation;document.body.classList.toggle('presentation',state.presentation);$('#presentation').textContent=state.presentation?'Debug mode':'Presentation mode'};
$$('[data-pixel]').forEach(b=>b.onclick=()=>loadPixel(...b.dataset.pixel.split(',').map(Number)));
$('#image').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();loadPixel(Math.floor((e.clientX-r.left)*256/r.width),Math.floor((e.clientY-r.top)*256/r.height))};

async function loadPixel(x,y){$('#status').textContent=`Loading exact trace (${x},${y})…`;try{const d=await fetch(`/api/trace?x=${x}&y=${y}&schema=d3.1-final`,{cache:'no-store'}).then(r=>r.json());if(d.status==='ERROR')throw Error(d.error);trace=d;selectedComponent=null;intervention=null;selected=d.paths[0]||null;renderAll();$('#status').textContent=`Pixel (${x},${y}) · ${d.paths.length} exact secondary paths · d3.1`;const requested=new URLSearchParams(location.search).get('path');if(requested){const p=d.paths.find(p=>p.id===requested);if(p)selectPath(p)}updateURL()}catch(e){$('#status').textContent='ERROR: '+e.message}}
function renderAll(){renderWhy();renderPartialPixel();renderCards();renderDecomposition();drawCumulative();applyFilters();renderComponents();drawDirections();renderDAG();selectPath(selected,false);renderSampler();$('#raw').textContent=JSON.stringify(trace,null,2);$('#counterfactualControls').style.display=trace.material?'grid':'none';$('#interventionResult').innerHTML='';$('#attributionIntervention').innerHTML='';$('#roughness').value=trace.material?.roughness??.5;$('#roughOut').value=fmt(+$('#roughness').value,3);baseDefault=toHex(trace.material?.base_color||[.5,.5,.5]);$('#baseColor').value=baseDefault;$('#specular').value=trace.material?.specular??1;$('#specOut').value=fmt(+$('#specular').value,3)}
function renderWhy(){const w=trace.why;$('#whySummary').classList.remove('empty');$('#whySummary').innerHTML=kv('Pixel',`(${w.pixel})`)+kv('Surface',w.surface)+kv('Shading regime',w.shading_regime)+kv('Material',w.material)+kv('Roughness',fmt(w.roughness))+kv('F0',fmt(w.F0))+kv('Dominant lighting',w.dominant_lighting.gmm_component==null?w.dominant_lighting.label:`GMM #${w.dominant_lighting.gmm_component} · ${w.dominant_lighting.label}`)+kv('Top 12 paths',fmt(100*w.top_12_fraction,3)+'%')+kv('Specular / Diffuse',w.specular_fraction==null?'N/A':`${fmt(100*w.specular_fraction,3)}% / ${fmt(100*w.diffuse_fraction,3)}%`)+kv('Reconstruction error',fmt(w.reconstruction_max_abs));$('#pixelSwatches').innerHTML=swatch('Recorded',w.recorded_rgb)+swatch('Reconstructed',w.reconstructed_rgb)}
function renderPartialPixel(){if(!trace)return;const raw=$('#partialN').value,n=raw==='all'?trace.paths.length:+raw,subset=trace.paths.slice(0,n).reduce((a,p)=>a.map((v,i)=>v+p.pixel_contribution[i]),[0,0,0]),partial=subset.map((v,i)=>v+trace.contribution_summary.background_direct[i]),remainder=trace.reconstruction.reconstructed.map((v,i)=>v-partial[i]);$('#partialPixel').innerHTML=metric('Selected subset',raw==='all'?'All paths':`Top ${n} paths`)+metric('Partial RGB',rgb(partial))+metric('Remainder RGB',rgb(remainder))+metric('Partial + remainder',rgb(partial.map((v,i)=>v+remainder[i])))+metric('Absolute error',rgb(trace.reconstruction.absolute_error))}
$('#partialN').onchange=renderPartialPixel;
function renderCards(){const p=trace.primary,s=trace.surface,m=trace.material;$('#primaryCard').innerHTML=metric('Pixel',`(${p.pixel})`)+metric('Sample coordinate',`(${p.sample_coordinate})`)+metric('Origin',rgb(p.origin))+metric('Direction',rgb(p.direction))+metric('Hit / t',p.hit?`teapot · ${fmt(p.t_hit)}`:'miss → background NeRF');$('#primaryRaw').textContent=JSON.stringify(p,null,2);$('#surfaceCard').innerHTML=s?metric('Position',rgb(s.world_position))+metric('Triangle',s.triangle_id)+metric('Barycentric',rgb(s.barycentric))+metric('UV',`(${s.uv.map(x=>fmt(x)).join(', ')})`)+metric('Geometric normal',rgb(s.geometric_normal))+metric('Shading normal',rgb(s.shading_normal)):metric('Surface','None — primary ray enters background NeRF');$('#surfaceRaw').textContent=JSON.stringify(s,null,2);$('#materialCard').innerHTML=m?metric('Base color',`<span class="colorDot" style="background:${toHex(m.base_color)}"></span>${rgb(m.base_color)}`)+metric('Roughness',fmt(m.roughness))+metric('Specular / F0',`${fmt(m.specular)} / ${fmt(m.F0)}`)+metric('IOR / metallic',`${fmt(m.ior)} / ${fmt(m.metallic)}`)+metric('BSDF',m.type):metric('Material','N/A for background pixel');$('#materialRaw').textContent=JSON.stringify(m,null,2)}
function renderDecomposition(){const c=trace.contribution_summary, total=Math.max(luminance(c.total_reconstructed),1e-12);const items=[['Diffuse',c.diffuse],['Specular',c.specular],['BSDF sampled',c.bsdf_sampled],['vMF sampled',c.vmf_sampled],['Visible',c.visible],['Occluded-zeroed',c.occluded_zeroed],['Background direct',c.background_direct]];$('#decomposition').innerHTML=items.map(([n,v])=>`<div class="barRow"><span>${n}</span><div class="bar"><i style="width:${100*clamp(luminance(v)/total)}%"></i></div><code>${fmt(100*luminance(v)/total,3)}%</code></div>`).join('')+metric('Attribution residual max',fmt(Math.max(...c.attribution_residual.map(Math.abs))))+metric('Lobe closure residual max',fmt(Math.max(...c.lobe_residual.map(Math.abs))));const x=$('#stacked').getContext('2d');x.clearRect(0,0,720,130);let left=25;[['diffuse','#45b9e8'],['specular','#ffc95b'],['background_direct','#8c77d7']].forEach(([k,col])=>{const w=650*clamp(luminance(c[k])/total);x.fillStyle=col;x.fillRect(left,35,w,40);x.fillStyle='#dce8f2';x.fillText(`${k} ${fmt(100*luminance(c[k])/total,3)}%`,left,95);left+=w})}
function drawCumulative(){const c=$('#cumulative'),x=c.getContext('2d'),paths=trace.paths;x.clearRect(0,0,c.width,c.height);x.strokeStyle='#263a4a';for(let i=0;i<=4;i++){const y=20+i*48;x.beginPath();x.moveTo(45,y);x.lineTo(700,y);x.stroke()}x.strokeStyle='#5ed7ff';x.lineWidth=2;x.beginPath();paths.forEach((p,i)=>{const px=45+650*Math.log1p(i)/Math.log1p(Math.max(paths.length-1,1)),py=220-190*clamp(p.cumulative_fraction);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#9fb2c1';x.fillText('paths (log scale)',590,237);x.fillText('100%',8,31);x.fillText('0%',18,222);$('#thresholds').innerHTML=Object.entries(trace.contribution_summary.paths_needed).map(([k,v])=>`<span class="badge">${+k*100}% → ${v??'not reached'} paths</span>`).join(' ')}

['sort','source','visibility','lobe','topN'].forEach(id=>$('#'+id).onchange=applyFilters);$('#componentFilter').oninput=applyFilters;
function applyFilters(){if(!trace)return;const source=$('#source').value,vis=$('#visibility').value,lobe=$('#lobe').value,comp=$('#componentFilter').value;filtered=trace.paths.filter(p=>(source==='all'||p.source===source)&&(vis==='all'||(vis==='visible'&&p.visible)||(vis==='occluded'&&p.occluded))&&(lobe==='all'||p.lobe===lobe)&&(comp===''||p.component===+comp));const sort=$('#sort').value;filtered.sort((a,b)=>(b[sort]??-Infinity)-(a[sort]??-Infinity));const n=$('#topN').value;if(n!=='all')filtered=filtered.slice(0,+n);const spacer=$('#vtableSpacer');spacer.style.height=`${filtered.length*34}px`;$('#vtable').scrollTop=0;renderVirtual();draw3D();drawDirections()}
$('#vtable').onscroll=renderVirtual;function renderVirtual(){const box=$('#vtable'),start=Math.max(0,Math.floor(box.scrollTop/34)-4),end=Math.min(filtered.length,start+20);$('#vtableRows').innerHTML=filtered.slice(start,end).map((p,j)=>`<div class="vrow ${selected?.id===p.id?'selected':''}" data-id="${p.id}" style="top:${(start+j)*34}px"><span>${p.id}</span><span>${p.source}</span><span>${p.visible?'1':'0'}</span><span class="pct">${fmt(100*p.energy_fraction,3)}% / ${fmt(100*p.cumulative_fraction,3)}%</span><span>${fmt(p.Li_luminance,3)}</span><span>${fmt(p.bsdf_pdf,3)}</span><span>${fmt(p.emitter_pdf,3)}</span><span>${fmt(p.mis_weight,3)}</span></div>`).join('');$$('.vrow').forEach(r=>r.onclick=()=>selectPath(trace.paths.find(p=>p.id===r.dataset.id)))}
function selectPath(p,push=true){selected=p;if(!p){$('#causalChain').innerHTML='No secondary path for a background pixel.';drawVolume();draw3D();return}renderVirtual();renderHow();draw3D();drawDirections();drawVolume();if(push)updateURL()}
function renderHow(){const p=selected,V=p.visible?1:0,q=p.selection_probability,ps=p.proposal_pdf,w=p.mis_weight,d=p.microfacet_diagnostic;const steps=[['① Sampling',`${p.source}${p.component==null?'':` · component #${p.component}`}\nwi ${rgb(p.wi)}\np_bsdf ${fmt(p.bsdf_pdf)}\np_emitter ${fmt(p.emitter_pdf)}`],['② Visibility',`occluded ${p.occluded}\nV = ${V}`],['③ Environment',`Li ${rgb(p.Li)}\nluminance ${fmt(p.Li_luminance)}`],['④ Material response',`f·cos ${rgb(p.bsdf_f_cos)}\ndiffuse ${rgb(p.diffuse_f_cos)}\nspecular ${rgb(p.specular_f_cos)}\nNoL ${fmt(p.cos_theta)} · NoV ${fmt(p.NoV)}\nD ${fmt(d.D)} · F ${rgb(d.F)} · G ${fmt(d.G)}\n${d.label}`],['⑤ MIS',`q ${fmt(q)}\np_selected ${fmt(ps)}\nbalance weight ${fmt(w)}`],['⑥ Contribution',`sample RGB ${rgb(p.sample_contribution)}\npixel RGB ${rgb(p.pixel_contribution)}\npixel share ${fmt(100*p.energy_fraction,4)}%`]];$('#causalChain').classList.remove('empty');$('#causalChain').innerHTML=steps.map(([a,b])=>`<div class="chainStep"><b>${a}</b><code>${b}</code></div>`).join('');const calc=p.Li.map((v,i)=>V*v*p.bsdf_f_cos[i]*w/(q*ps));$('#formula').innerHTML=`<p><code>C = V × Li × (f·cosθ) × w_balance / (q × p_selected)</code></p>${metric('V',V)}${metric('Li',rgb(p.Li))}${metric('f·cosθ',rgb(p.bsdf_f_cos))}${metric('w_balance',fmt(w))}${metric('q × p_selected',fmt(q*ps))}${metric('Substituted result',rgb(calc))}${metric('Stored sample result',rgb(p.sample_contribution))}<p class="diagnostic">D/F/G are ${d.label}; the exact response above is the full Mitsuba principled plugin value.</p>`}

function renderDAG(){const tabMap={camera:'why',primary_ray:'why',geometry:'why',surface:'why',material:'whatif',sampler:'where',wi:'where',visibility:'how',nerf:'nerf',Li:'nerf',bsdf:'how',mis:'how',contribution:'why',pixel_rgb:'why'};$('#dag').innerHTML=trace.causal_graph.nodes.map(n=>`<span class="dagNode" data-node="${n}">${n.replace('_',' ')}</span>`).join('');$$('.dagNode').forEach(n=>n.onclick=()=>{setTab(tabMap[n.dataset.node]);n.classList.add('current')})}
function renderComponents(){if(!trace)return;$('#componentList').innerHTML=trace.component_attribution.slice(0,20).map(c=>`<div class="component ${selectedComponent===c.component?'active':''}" data-component="${c.component}"><b>#${c.component}</b><span>centroid ${c.centroid.map(x=>fmt(x,3)).join(', ')}</span><code>${fmt(100*c.fraction,3)}%</code></div>`).join('');$$('.component').forEach(e=>e.onclick=()=>{selectedComponent=+e.dataset.component;$('#componentFilter').value=selectedComponent;applyFilters();renderComponents()})}
function sphereXY(d){return [(Math.atan2(d[1],d[0])+Math.PI)/(2*Math.PI),Math.acos(clamp(d[2],-1,1))/Math.PI]}
function drawDirections(){if(!trace)return;const c=$('#directions'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);const g=x.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,'#172a3c');g.addColorStop(1,'#080d12');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.strokeStyle='#263d50';for(let i=1;i<6;i++){x.beginPath();x.moveTo(i*c.width/6,0);x.lineTo(i*c.width/6,c.height);x.stroke()}const surf=trace.surface?.world_position;trace.component_attribution.slice(0,30).forEach(cmp=>{if(!surf)return;const d=cmp.centroid.map((v,i)=>v-surf[i]),n=Math.hypot(...d),u=sphereXY(d.map(v=>v/n));x.fillStyle=cmp.component===selectedComponent?'#ffd15a':'#ff974a';x.beginPath();x.arc(u[0]*c.width,u[1]*c.height,3+12*Math.sqrt(clamp(cmp.fraction)),0,7);x.fill();x.fillText('#'+cmp.component,u[0]*c.width+5,u[1]*c.height)});trace.paths.slice(0,300).forEach(p=>{const u=sphereXY(p.wi);x.fillStyle=p.id===selected?.id?'#fff36a':p.source==='vMF/emitter'?'#4de4bc':'#65aaff';x.globalAlpha=p.id===selected?.id?1:.28;x.fillRect(u[0]*c.width,u[1]*c.height,2,2)});x.globalAlpha=1}

// Lightweight WebGL line viewer: GPU rendering, CPU projected picking, orbit/pan/zoom.
const gl=$('#path3d').getContext('webgl',{antialias:true});let glProgram=null,glBuffer=null,drawnPaths=[];
function initGL(){if(!gl)return;const vs=`attribute vec3 p;attribute vec4 c;uniform vec3 center;uniform vec4 view;uniform float panY;varying vec4 color;void main(){vec3 v=p-center;float cy=cos(view.x),sy=sin(view.x),cp=cos(view.y),sp=sin(view.y);v=vec3(cy*v.x+sy*v.z,v.y,-sy*v.x+cy*v.z);v=vec3(v.x,cp*v.y-sp*v.z,sp*v.y+cp*v.z);gl_Position=vec4(v.x*view.z+view.w,v.y*view.z+panY,0,1);color=c;} `,fs=`precision mediump float;varying vec4 color;void main(){gl_FragColor=color;}`;const sh=(t,s)=>{const q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);return q};glProgram=gl.createProgram();gl.attachShader(glProgram,sh(gl.VERTEX_SHADER,vs));gl.attachShader(glProgram,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(glProgram);glBuffer=gl.createBuffer();gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA)}initGL();
function addLine(a,b,col,arr){arr.push(...a,...col,...b,...col)}
function draw3D(){if(!gl||!trace)return;const center=trace.surface?.world_position||trace.primary.origin,arr=[];drawnPaths=[];if(meshEdges.length&&!state.isolated)for(const e of meshEdges)addLine(e[0],e[1],[.25,.38,.48,.18],arr);if(trace.surface){addLine(trace.primary.origin,trace.surface.world_position,[.85,.88,.92,.9],arr);addLine(trace.surface.world_position,trace.surface.world_position.map((v,i)=>v+trace.surface.shading_normal[i]*.25),[.45,.68,1,1],arr);let paths=state.isolated&&selected?[selected]:trace.paths.slice(0,$('#rayCount').value==='all'?trace.paths.length:+$('#rayCount').value);paths.forEach(p=>{const end=p.origin.map((v,i)=>v+p.wi[i]*.65),col=p.id===selected?.id?[1,.82,.2,1]:p.visible?[.2,.9,.72,.18+clamp(p.energy_fraction*30,0,.7)]:[1,.3,.4,.4];addLine(p.origin,end,col,arr);drawnPaths.push(p)});if($('#showClusters').checked)trace.component_attribution.slice(0,30).forEach(c=>{const d=c.centroid.map((v,i)=>v-trace.surface.world_position[i]),n=Math.hypot(...d)||1,q=trace.surface.world_position.map((v,i)=>v+d[i]/n*.72),s=.018,col=c.component===selectedComponent?[1,.82,.2,1]:[1,.48,.2,.75];for(let i=0;i<3;i++){const a=[...q],b=[...q];a[i]-=s;b[i]+=s;addLine(a,b,col,arr)}});if(state.tab==='nerf'&&trace.nerf_diagnostic){const n=trace.nerf_diagnostic,t=n.t[volumeIndex],q=n.origin_external.map((v,i)=>v+n.direction_external[i]*t),s=.025;for(let i=0;i<3;i++){const a=[...q],b=[...q];a[i]-=s;b[i]+=s;addLine(a,b,[1,.2,1,1],arr)}}}gl.viewport(0,0,gl.canvas.width,gl.canvas.height);gl.clearColor(.03,.05,.07,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(glProgram);gl.bindBuffer(gl.ARRAY_BUFFER,glBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(arr),gl.DYNAMIC_DRAW);const ps=gl.getAttribLocation(glProgram,'p'),cs=gl.getAttribLocation(glProgram,'c');gl.enableVertexAttribArray(ps);gl.vertexAttribPointer(ps,3,gl.FLOAT,false,28,0);gl.enableVertexAttribArray(cs);gl.vertexAttribPointer(cs,4,gl.FLOAT,false,28,12);gl.uniform3fv(gl.getUniformLocation(glProgram,'center'),center);gl.uniform4f(gl.getUniformLocation(glProgram,'view'),state.yaw,state.pitch,state.zoom,state.panX);gl.uniform1f(gl.getUniformLocation(glProgram,'panY'),state.panY);gl.drawArrays(gl.LINES,0,arr.length/7)}
function project(v){const c=trace.surface?.world_position||trace.primary.origin;let x=v[0]-c[0],y=v[1]-c[1],z=v[2]-c[2],cy=Math.cos(state.yaw),sy=Math.sin(state.yaw),cp=Math.cos(state.pitch),sp=Math.sin(state.pitch),x1=cy*x+sy*z,z1=-sy*x+cy*z,y1=cp*y-sp*z1;return [(x1*state.zoom+state.panX+1)*425,(1-(y1*state.zoom+state.panY))*240]}
let drag=null;$('#path3d').onmousedown=e=>drag=[e.clientX,e.clientY,e.shiftKey];window.onmouseup=()=>drag=null;window.onmousemove=e=>{if(!drag)return;const dx=e.clientX-drag[0],dy=e.clientY-drag[1];if(drag[2]){state.panX+=dx/400;state.panY-=dy/300}else{state.yaw+=dx*.008;state.pitch+=dy*.008}drag=[e.clientX,e.clientY,drag[2]];draw3D()};$('#path3d').onwheel=e=>{e.preventDefault();state.zoom*=e.deltaY>0?.9:1.1;draw3D()};$('#path3d').onclick=e=>{if(Math.hypot(e.movementX,e.movementY)>3||!trace.surface)return;const r=e.currentTarget.getBoundingClientRect(),q=[(e.clientX-r.left)*850/r.width,(e.clientY-r.top)*480/r.height];let best=null,bd=12;for(const p of drawnPaths){const a=project(p.origin),b=project(p.origin.map((v,i)=>v+p.wi[i]*.65)),vx=b[0]-a[0],vy=b[1]-a[1],t=clamp(((q[0]-a[0])*vx+(q[1]-a[1])*vy)/(vx*vx+vy*vy)),d=Math.hypot(q[0]-(a[0]+t*vx),q[1]-(a[1]+t*vy));if(d<bd){bd=d;best=p}}if(best)selectPath(best)};$('#reset3d').onclick=()=>{Object.assign(state,{yaw:-.65,pitch:.3,zoom:1.25,panX:0,panY:0});draw3D()};$('#isolate').onclick=()=>{state.isolated=!state.isolated;$('#isolate').classList.toggle('active',state.isolated);draw3D()};$('#rayCount').onchange=draw3D;$('#showClusters').onchange=draw3D;

function drawVolume(){if(!trace)return;const n=trace.nerf_diagnostic,c=$('#volume'),x=c.getContext('2d'),keys=[['sigma','#ffbf55'],['transmittance','#52d6b1'],['weight','#59aaff'],['contribution_i','#e76eff']];x.clearRect(0,0,c.width,c.height);keys.forEach(([k,col])=>{const vals=k==='contribution_i'?n[k].map(luminance):n[k],mx=Math.max(...vals,1e-12);x.strokeStyle=col;x.beginPath();vals.forEach((v,i)=>{const px=35+i*(c.width-55)/(vals.length-1),py=c.height-25-v/mx*(c.height-45);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()});x.fillStyle='#fff';x.fillText(`sample ${volumeIndex}`,40,15);const t=n.t[volumeIndex],pos=n.origin_external.map((v,i)=>v+n.direction_external[i]*t);$('#volumeSample').innerHTML=metric('Index / t',`${volumeIndex} / ${fmt(t)}`)+metric('Position',rgb(pos))+metric('sigma / alpha',`${fmt(n.sigma[volumeIndex])} / ${fmt(n.alpha[volumeIndex])}`)+metric('T / weight',`${fmt(n.transmittance[volumeIndex])} / ${fmt(n.weight[volumeIndex])}`)+metric('RGB contribution',rgb(n.contribution_i[volumeIndex]));const drift=Math.max(...n.final_Li.map((v,i)=>Math.abs(v-n.stored_selected_path_Li[i])));$('#nerfClosure').innerHTML=metric('Diagnostic path',n.path_id||'background primary')+metric('Li retrace',rgb(n.final_Li))+metric('Σ weight·rgb',rgb(n.sum_weighted_rgb))+metric('Internal closure',fmt(Math.max(...n.final_Li.map((v,i)=>Math.abs(v-n.sum_weighted_rgb[i])))))+metric('Stored Li vs diagnostic drift',fmt(drift));$('#volumeLegend').innerHTML=keys.map(([k,c])=>`<span style="color:${c}">● ${k}</span>`).join(' &nbsp; ');draw3D()}
$('#volume').onclick=e=>{const r=e.currentTarget.getBoundingClientRect(),last=Math.max(0,trace.nerf_diagnostic.t.length-1);volumeIndex=Math.round(clamp((e.clientX-r.left)/r.width)*last);drawVolume()};

$('#roughness').oninput=()=>$('#roughOut').value=fmt(+$('#roughness').value,3);$('#specular').oninput=()=>$('#specOut').value=fmt(+$('#specular').value,3);function toHex(v){return '#'+v.map(x=>Math.round(255*clamp(x)).toString(16).padStart(2,'0')).join('')}function fromHex(s){return [1,3,5].map(i=>parseInt(s.slice(i,i+2),16)/255)}
async function runIntervention(mode){if(!trace.material)return;const rough=+$('#roughness').value,specular=+$('#specular').value,baseHex=$('#baseColor').value,params=new URLSearchParams({mode,x:trace.pixel[0],y:trace.pixel[1],roughness:rough,specular});if(baseHex!==baseDefault)params.set('base_color',fromHex(baseHex).join(','));$('#interventionResult').innerHTML=`Running ${mode} on GPU1…`;try{intervention=await fetch('/api/intervention?'+params).then(r=>r.json());if(intervention.status==='ERROR')throw Error(intervention.error);const a=intervention.original.rgb,b=intervention.result.rgb;$('#interventionResult').innerHTML=`<h3>${intervention.mode}</h3>${metric('Roughness',`${fmt(trace.material.roughness)} → ${fmt(rough)}`)}${metric('RGB',`${rgb(a)} → ${rgb(b)}`)}${metric('Diffuse fraction',fmt(intervention.result.diffuse_fraction))}${metric('Specular fraction',fmt(intervention.result.specular_fraction))}${metric('Top 10 concentration',fmt(intervention.result.top_fractions['10']))}${metric('Reproducibility error',fmt(intervention.reproducibility_max_abs))}<p class="diagnostic">${intervention.causal_semantics}</p>`}catch(e){$('#interventionResult').textContent='ERROR: '+e.message}}
$('#runFrozen').onclick=()=>runIntervention('frozen');$('#runFull').onclick=()=>runIntervention('full');
$('#removeComponent').onclick=()=>{if(selectedComponent==null)return $('#attributionIntervention').textContent='Select a GMM component in WHERE first.';const removed=trace.paths.filter(p=>p.component===selectedComponent).reduce((a,p)=>a.map((v,i)=>v+p.pixel_contribution[i]),[0,0,0]),after=trace.reconstruction.reconstructed.map((v,i)=>v-removed[i]);$('#attributionIntervention').innerHTML=metric('Mode','Attribution-only')+metric('Removed component','#'+selectedComponent)+metric('Before',rgb(trace.reconstruction.reconstructed))+metric('After',rgb(after))+metric('Removed RGB',rgb(removed))};
$('#forceOccluded').onclick=()=>{if(!selected)return;const after=trace.reconstruction.reconstructed.map((v,i)=>v-selected.pixel_contribution[i]);$('#attributionIntervention').innerHTML=metric('Mode','Hypothetical force V=0')+metric('Path',selected.id)+metric('Path before',rgb(selected.pixel_contribution))+metric('Path after','(0, 0, 0)')+metric('Pixel before',rgb(trace.reconstruction.reconstructed))+metric('Pixel after',rgb(after))};
async function renderSampler(){if(!samplerData)try{samplerData=await fetch('/api/sampler').then(r=>r.json())}catch{return}const rows=Object.entries(samplerData.spp).map(([s,d])=>`<tr><td>${s}</td><td>${fmt(d.cosine.predicted_estimator_variance)}</td><td>${fmt(d.mis.predicted_estimator_variance)}</td><td>${fmt(d.mis_improvement_vs_cosine.variance_reduction_percent,4)}%</td><td>${d.cosine.firefly_count} → ${d.mis.firefly_count}</td></tr>`).join('');$('#samplerComparison').innerHTML=`<table><tr><th>SPP</th><th>Cosine variance</th><th>MIS variance</th><th>Reduction</th><th>Fireflies</th></tr>${rows}</table><p class="diagnostic">Fixed D1 A/B data for the same camera/material/NeRF and seed family.</p>`}

function download(name,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
$('#exportBundle').onclick=()=>{if(!trace)return;const prefix=`investigation_${trace.pixel.join('_')}`;download(prefix+'_pixel_trace.json',JSON.stringify(trace,null,2));download(prefix+'_selected_path.json',JSON.stringify(selected,null,2));download(prefix+'_contribution_summary.json',JSON.stringify(trace.contribution_summary,null,2));if(intervention)download(prefix+'_intervention.json',JSON.stringify(intervention,null,2));[$('#cumulative'),$('#path3d')].forEach((c,i)=>{try{const a=document.createElement('a');a.download=prefix+(i?'_paths3d.png':'_cumulative.png');a.href=c.toDataURL();a.click()}catch{}});const html=`<!doctype html><meta charset=utf-8><title>${prefix}</title><h1>D3 Investigation ${trace.pixel}</h1><pre>${escapeHTML(JSON.stringify({why:trace.why,selected_path:selected,summary:trace.contribution_summary,intervention},null,2))}</pre>`;download(prefix+'_report.html',html,'text/html')};function escapeHTML(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}

Promise.all([fetch('/reimpl/d3_causal_explorer/assets/teapot_edges.json').then(r=>r.ok?r.json():[]).catch(()=>[]),fetch('/api/sampler').then(r=>r.json()).catch(()=>null)]).then(([m,s])=>{meshEdges=m;samplerData=s;const q=new URLSearchParams(location.search),px=(q.get('pixel')||'151,109').split(',').map(Number);state.tab=q.get('tab')||'why';setTab(state.tab);loadPixel(...px)});
